ALTER TABLE analisis_riesgo
ADD COLUMN IF NOT EXISTS contenido_analisis TEXT,
ADD COLUMN IF NOT EXISTS estado_riesgo VARCHAR(50),
ADD COLUMN IF NOT EXISTS fecha_analisis DATE,
ADD COLUMN IF NOT EXISTS creado_en TIMESTAMP,
ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMP;